name: Continuous Delivery
on: [push, pull_request]

jobs:
  check:
    name: Static check and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Run static check
        run: npx nx lint crew
      # TODO: implement unit test CI for later
  deploy:
    needs: check
    name: Deploy app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: env DOCKER_BUILDKIT=1 flyctl deploy --remote-only -c packages/crew/fly.toml --dockerfile packages/crew/Dockerfile --build-secret NEXT_PUBLIC_MIXPANEL_ID=$NEXT_PUBLIC_MIXPANEL_ID
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NEXT_PUBLIC_MIXPANEL_ID: ${{ secrets.NEXT_PUBLIC_MIXPANEL_ID }}
