name: Fly Deploy
on:
  workflow_run:
    workflows: ['Quality Checks / Static check and unit tests']
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c packages/crew/fly.toml --dockerfile packages/crew/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
