name: Quality Checks
on: [push, pull_request]

jobs:
  check:
    name: Static check and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run static check
        run: npx nx lint crew
      # TODO: implement unit test CI for later
